### PR TITLE
Updated Dutch translations

### PR DESCRIPTION
**Pull request by Voxxie**

### CODE REVIEW

**Comment by SukramJ** [comment]
Please check nl.json. There should be not update necessary.

**Comment by Voxxie** [comment]
Sorry Github is new for me. 
I now know how to do it in the feature. 

nl.json is updated, the file contained a wrong entry.

**Comment by SukramJ** [comment]
Please check the english translation: "own" has been removed!

**Comment by Voxxie** [comment]
I know, see commis 8a7dab6

**Comment by SukramJ** [comment]
And what is the meaning of "eigen"??

**Comment by Voxxie** [comment]
Double checked the translation and added the new ones.

**Comment by SukramJ** [comment]
Thanks for your support, but you should read same basic git tutorials.
Maybe [this](https://developers.home-assistant.io/docs/development_submitting) helps.
Always create a new branch based on the current level branch. Then add your changes. 

As already mentioned:
Due to your latest merge your branch contains to many commits that are **not related** to your translation.
Do not use Merge to update your branch.
Please rebase your branch to get rid of these additional commits.

```
git fetch upstream devel
git rebase upstream/devel
git push -f
```

**Comment by Voxxie** [comment]
I did a fetch and rebase,  but it still gives 16 commits on two files.

**Comment by SukramJ** [comment]
Looks good now.
Those 16 commits are your commits, so it is OK.

**Pull request merged**
