### PR TITLE
Add dependabot for gh actions

### PR DESCRIPTION
**Pull request by mrueg**
Add a [dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions) action for github action, which will send automated PRs for the used actions to update them.

### CODE REVIEW

**Comment by SukramJ** [comment]
Thanks for your contribution.
I deliberately chose not to use dependabot here, which unfortunately makes it a little more complicated, since the dependencies are essentially determined by HA and pytest-homeassistant-custom-component (testing), and so the latest versions cannot be installed.

**Comment by mrueg** [comment]
Thanks for the quick response! Maybe I was not super clear what this does.
It will update only the actions that you have defined in your CI pipeline and won't touch python deps.

e.g. https://github.com/danielperna84/custom_homematic/blob/devel/.github/workflows/pylint.yml#L21 is currently v5

**Comment by SukramJ** [comment]
Ok, nice.

Could you please create a PR for https://github.com/danielperna84/hahomematic too?

**Comment by mrueg** [comment]
Sure, will do!

**Pull request merged**
